#!/bin/bash

case "$1" in
    start)
        ./manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f /var/run/my_process.pid ]; then
            pid=$(cat /var/run/my_process.pid)
            kill $pid
            rm /var/run/my_process.pid
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
        ;;
    restart)
        if [ -f /var/run/my_process.pid ]; then
            pid=$(cat /var/run/my_process.pid)
            kill $pid
            rm /var/run/my_process.pid
            ./manage_my_process &
            echo $! > /var/run/my_process.pid
            echo "manage_my_process restarted"
        else
            echo "manage_my_process is not running. Starting it..."
            ./manage_my_process &
            echo $! > /var/run/my_process.pid
            echo "manage_my_process started"
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
