#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays this data.

# Use awk to extract the visitor IP and HTTP status code from the Apache log file
# Then use sort to count and group the occurrences of each combination and sort them by the number of occurrences in descending order
awk '{ print $1, $9 }' apache-access.log | sort | uniq -c | sort -rn | awk '{ print $1, $2, $3 }'
